### PR TITLE
Process Video

### PR DESCRIPTION
**Pull request by ashwin-phadke**
- Added file to process videos using the lanenet-lane-detection algorithm.
- Convert videos to frames.
- Process frames in batch using batch processing function.
- Save and stitch the frames together to generate video.

### CODE REVIEW

**Comment by ashwin-phadke** [comment]
Issue #196

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke Sorry I have made some changes on the repo so the script you supply may not work correctly:）

**Comment by ashwin-phadke** [comment]
Let me check the changes.

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke Thanks a lot:)

**Comment by ashwin-phadke** [comment]
As your network and checking inference is same I suppose and only the test_lanenet has changed, maybe this script will still be compatible with the network. What do you say?

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke No some of your imported module is no longer existed:)

**Comment by zorrobyte** [comment]
@ashwin-phadke Thank you for your work here. Such would be nice to have in repo.

**Comment by ashwin-phadke** [comment]
Hey @zorrobyte thank you for the kind words.

**Comment by zhuanghongjie** [comment]
@ashwin-phadke Is there a new one for detecting video since the change has been made?Thank you for your share.Appreciated so much.

**Comment by ashwin-phadke** [comment]
> @ashwin-phadke Is there a new one for detecting video since the change has been made?Thank you for your share.Appreciated so much.

I am working on it . Will be there soon I hope.

**Pull request closed without merging**
